[Variables]
; color settings
innerRingColor=#GlassWhite#
outerRingColor=#AcidGreen#,200
;pieColor=194,189,237,255
;pieColor=250,100,100,200
pieColor=#Accent1#
textMainColor=#Accent2#
textSubColor=#Accent3#
bgBarColor=10,10,10,200

;-------------- Colour selection --------------

Accent1=#MugiLavender#,190
Accent2=#GlassWhite#,175
Accent3=#GlassGrey#,175
Accent4=#DarkUV#

DarkUV=219,87,124
LightUV=255,127,165
MugiLavender=206,154,193
AcidGreen=88,219,105
GlassGrey=150,150,150
GlassBlack=0,0,0
GlassWhite=255,255,255

AkaiRed=255,100,100
AzusaTeal=115,182,141

; size and scaling
radius=(#WORKAREAWIDTH#/48*1.25)
;30
innerRadius=(#radius#*0.65) 
edging=(#radius#*0.25) 
orient=left
pieSize=1

; show and hide skin components
hidePieBg=0
hideDivider=1
hideSubText=0

; font attributes
mainFont=Lexend
subFont=Lexend
subTwoLines=0